// Code generated by protoc-gen-go.
// source: eventmaster.proto
// DO NOT EDIT!

/*
Package eventmaster is a generated protocol buffer package.

It is generated from these files:
	eventmaster.proto

It has these top-level messages:
	Event
	WriteResponse
	HealthcheckRequest
	HealthcheckResponse
*/
package eventmaster

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event struct {
	Timestamp int64    `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Dc        string   `protobuf:"bytes,2,opt,name=dc" json:"dc,omitempty"`
	TopicName string   `protobuf:"bytes,3,opt,name=topic_name,json=topicName" json:"topic_name,omitempty"`
	Tags      []string `protobuf:"bytes,4,rep,name=tags" json:"tags,omitempty"`
	Host      string   `protobuf:"bytes,5,opt,name=host" json:"host,omitempty"`
	User      string   `protobuf:"bytes,6,opt,name=user" json:"user,omitempty"`
	Data      string   `protobuf:"bytes,7,opt,name=data" json:"data,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Event) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Event) GetDc() string {
	if m != nil {
		return m.Dc
	}
	return ""
}

func (m *Event) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *Event) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Event) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Event) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Event) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type WriteResponse struct {
	Errcode int32  `protobuf:"varint,1,opt,name=errcode" json:"errcode,omitempty"`
	Errmsg  string `protobuf:"bytes,2,opt,name=errmsg" json:"errmsg,omitempty"`
}

func (m *WriteResponse) Reset()                    { *m = WriteResponse{} }
func (m *WriteResponse) String() string            { return proto.CompactTextString(m) }
func (*WriteResponse) ProtoMessage()               {}
func (*WriteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *WriteResponse) GetErrcode() int32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *WriteResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

type HealthcheckRequest struct {
}

func (m *HealthcheckRequest) Reset()                    { *m = HealthcheckRequest{} }
func (m *HealthcheckRequest) String() string            { return proto.CompactTextString(m) }
func (*HealthcheckRequest) ProtoMessage()               {}
func (*HealthcheckRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type HealthcheckResponse struct {
	Response string `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
}

func (m *HealthcheckResponse) Reset()                    { *m = HealthcheckResponse{} }
func (m *HealthcheckResponse) String() string            { return proto.CompactTextString(m) }
func (*HealthcheckResponse) ProtoMessage()               {}
func (*HealthcheckResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *HealthcheckResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func init() {
	proto.RegisterType((*Event)(nil), "eventmaster.Event")
	proto.RegisterType((*WriteResponse)(nil), "eventmaster.WriteResponse")
	proto.RegisterType((*HealthcheckRequest)(nil), "eventmaster.HealthcheckRequest")
	proto.RegisterType((*HealthcheckResponse)(nil), "eventmaster.HealthcheckResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for EventMaster service

type EventMasterClient interface {
	Track(ctx context.Context, in *Event, opts ...grpc.CallOption) (*WriteResponse, error)
	Healthcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error)
}

type eventMasterClient struct {
	cc *grpc.ClientConn
}

func NewEventMasterClient(cc *grpc.ClientConn) EventMasterClient {
	return &eventMasterClient{cc}
}

func (c *eventMasterClient) Track(ctx context.Context, in *Event, opts ...grpc.CallOption) (*WriteResponse, error) {
	out := new(WriteResponse)
	err := grpc.Invoke(ctx, "/eventmaster.EventMaster/Track", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventMasterClient) Healthcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error) {
	out := new(HealthcheckResponse)
	err := grpc.Invoke(ctx, "/eventmaster.EventMaster/Healthcheck", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EventMaster service

type EventMasterServer interface {
	Track(context.Context, *Event) (*WriteResponse, error)
	Healthcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error)
}

func RegisterEventMasterServer(s *grpc.Server, srv EventMasterServer) {
	s.RegisterService(&_EventMaster_serviceDesc, srv)
}

func _EventMaster_Track_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventMasterServer).Track(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eventmaster.EventMaster/Track",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventMasterServer).Track(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventMaster_Healthcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthcheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventMasterServer).Healthcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eventmaster.EventMaster/Healthcheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventMasterServer).Healthcheck(ctx, req.(*HealthcheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventMaster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "eventmaster.EventMaster",
	HandlerType: (*EventMasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Track",
			Handler:    _EventMaster_Track_Handler,
		},
		{
			MethodName: "Healthcheck",
			Handler:    _EventMaster_Healthcheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eventmaster.proto",
}

func init() { proto.RegisterFile("eventmaster.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x91, 0x41, 0x4b, 0xf4, 0x30,
	0x10, 0x86, 0xbf, 0xee, 0x6e, 0x77, 0xbf, 0x4e, 0x51, 0x70, 0x14, 0x09, 0x45, 0xb1, 0xf4, 0xe4,
	0x69, 0x41, 0x3d, 0x79, 0xf4, 0x20, 0x78, 0xd1, 0x43, 0x10, 0x3c, 0x4a, 0x4c, 0x87, 0x6d, 0x59,
	0xdb, 0xd4, 0x24, 0xeb, 0xaf, 0xf1, 0xe8, 0x0f, 0x35, 0xc9, 0x76, 0xb5, 0x45, 0xbc, 0x3d, 0xf3,
	0xf4, 0x65, 0x3a, 0x33, 0x81, 0x03, 0x7a, 0xa7, 0xd6, 0x36, 0xc2, 0x58, 0xd2, 0xcb, 0x4e, 0x2b,
	0xab, 0x30, 0x1d, 0xa8, 0xe2, 0x33, 0x82, 0xf8, 0xd6, 0xd7, 0x78, 0x02, 0x89, 0xad, 0x1b, 0x32,
	0x56, 0x34, 0x1d, 0x8b, 0xf2, 0xe8, 0x7c, 0xca, 0x7f, 0x04, 0xee, 0xc3, 0xa4, 0x94, 0x6c, 0xe2,
	0x74, 0xc2, 0x1d, 0xe1, 0x29, 0x80, 0x55, 0x5d, 0x2d, 0x9f, 0x5b, 0xd1, 0x10, 0x9b, 0x06, 0x9f,
	0x04, 0xf3, 0xe0, 0x04, 0x22, 0xcc, 0xac, 0x58, 0x19, 0x36, 0xcb, 0xa7, 0xee, 0x43, 0x60, 0xef,
	0x2a, 0x65, 0x2c, 0x8b, 0x43, 0x38, 0xb0, 0x77, 0x1b, 0x43, 0x9a, 0xcd, 0xb7, 0xce, 0xb3, 0x77,
	0xa5, 0xb0, 0x82, 0x2d, 0xb6, 0xce, 0x73, 0x71, 0x03, 0x7b, 0x4f, 0xba, 0xb6, 0xc4, 0xc9, 0x74,
	0xaa, 0x35, 0x84, 0x0c, 0x16, 0xa4, 0xb5, 0x54, 0x25, 0x85, 0x59, 0x63, 0xbe, 0x2b, 0xf1, 0x18,
	0xe6, 0x0e, 0x1b, 0xb3, 0xea, 0xa7, 0xed, 0xab, 0xe2, 0x08, 0xf0, 0x8e, 0xc4, 0xab, 0xad, 0x64,
	0x45, 0x72, 0xcd, 0xe9, 0x6d, 0xe3, 0x56, 0x2b, 0x2e, 0xe0, 0x70, 0x64, 0xfb, 0xf6, 0x19, 0xfc,
	0xd7, 0x3d, 0x87, 0xfe, 0x09, 0xff, 0xae, 0x2f, 0x3f, 0x22, 0x48, 0xc3, 0xc9, 0xee, 0xc3, 0x09,
	0xf1, 0x1a, 0xe2, 0x47, 0x2d, 0xe4, 0x1a, 0x71, 0x39, 0x3c, 0x76, 0x88, 0x64, 0xd9, 0xc8, 0x8d,
	0x76, 0x28, 0xfe, 0x21, 0x87, 0x74, 0xf0, 0x77, 0x3c, 0x1b, 0x85, 0x7f, 0x4f, 0x9b, 0xe5, 0x7f,
	0x07, 0x76, 0x3d, 0x5f, 0xe6, 0xe1, 0x95, 0xaf, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x20, 0x3e,
	0xe3, 0x2d, 0xfa, 0x01, 0x00, 0x00,
}
