// Code generated by protoc-gen-go.
// source: eventmaster.proto
// DO NOT EDIT!

/*
Package eventmaster is a generated protocol buffer package.

It is generated from these files:
	eventmaster.proto

It has these top-level messages:
	Event
	Query
	Topic
	UpdateTopicRequest
	DeleteTopicRequest
	Dc
	UpdateDcRequest
	WriteResponse
*/
package eventmaster

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event struct {
	EventId       string   `protobuf:"bytes,1,opt,name=event_id,json=eventId" json:"event_id,omitempty"`
	ParentEventId string   `protobuf:"bytes,2,opt,name=parent_event_id,json=parentEventId" json:"parent_event_id,omitempty"`
	EventTime     int64    `protobuf:"varint,3,opt,name=event_time,json=eventTime" json:"event_time,omitempty"`
	Dc            string   `protobuf:"bytes,4,opt,name=dc" json:"dc,omitempty"`
	TopicName     string   `protobuf:"bytes,5,opt,name=topic_name,json=topicName" json:"topic_name,omitempty"`
	TagSet        []string `protobuf:"bytes,6,rep,name=tag_set,json=tagSet" json:"tag_set,omitempty"`
	Host          string   `protobuf:"bytes,7,opt,name=host" json:"host,omitempty"`
	TargetHostSet []string `protobuf:"bytes,8,rep,name=target_host_set,json=targetHostSet" json:"target_host_set,omitempty"`
	User          string   `protobuf:"bytes,9,opt,name=user" json:"user,omitempty"`
	Data          []byte   `protobuf:"bytes,10,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Event) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *Event) GetParentEventId() string {
	if m != nil {
		return m.ParentEventId
	}
	return ""
}

func (m *Event) GetEventTime() int64 {
	if m != nil {
		return m.EventTime
	}
	return 0
}

func (m *Event) GetDc() string {
	if m != nil {
		return m.Dc
	}
	return ""
}

func (m *Event) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *Event) GetTagSet() []string {
	if m != nil {
		return m.TagSet
	}
	return nil
}

func (m *Event) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Event) GetTargetHostSet() []string {
	if m != nil {
		return m.TargetHostSet
	}
	return nil
}

func (m *Event) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Event) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Query struct {
	Dc                []string `protobuf:"bytes,1,rep,name=dc" json:"dc,omitempty"`
	Host              []string `protobuf:"bytes,2,rep,name=host" json:"host,omitempty"`
	TargetHostSet     []string `protobuf:"bytes,3,rep,name=target_host_set,json=targetHostSet" json:"target_host_set,omitempty"`
	User              []string `protobuf:"bytes,4,rep,name=user" json:"user,omitempty"`
	TopicName         []string `protobuf:"bytes,5,rep,name=topic_name,json=topicName" json:"topic_name,omitempty"`
	TagSet            []string `protobuf:"bytes,6,rep,name=tag_set,json=tagSet" json:"tag_set,omitempty"`
	ParentEventId     []string `protobuf:"bytes,7,rep,name=parent_event_id,json=parentEventId" json:"parent_event_id,omitempty"`
	Data              string   `protobuf:"bytes,8,opt,name=data" json:"data,omitempty"`
	StartEventTime    int64    `protobuf:"varint,9,opt,name=start_event_time,json=startEventTime" json:"start_event_time,omitempty"`
	EndEventTime      int64    `protobuf:"varint,10,opt,name=end_event_time,json=endEventTime" json:"end_event_time,omitempty"`
	StartReceivedTime int64    `protobuf:"varint,11,opt,name=start_received_time,json=startReceivedTime" json:"start_received_time,omitempty"`
	EndReceivedTime   int64    `protobuf:"varint,12,opt,name=end_received_time,json=endReceivedTime" json:"end_received_time,omitempty"`
	SortField         []string `protobuf:"bytes,13,rep,name=sort_field,json=sortField" json:"sort_field,omitempty"`
	SortAscending     []bool   `protobuf:"varint,14,rep,packed,name=sort_ascending,json=sortAscending" json:"sort_ascending,omitempty"`
	Start             int32    `protobuf:"varint,15,opt,name=start" json:"start,omitempty"`
	Limit             int32    `protobuf:"varint,16,opt,name=limit" json:"limit,omitempty"`
}

func (m *Query) Reset()                    { *m = Query{} }
func (m *Query) String() string            { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()               {}
func (*Query) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Query) GetDc() []string {
	if m != nil {
		return m.Dc
	}
	return nil
}

func (m *Query) GetHost() []string {
	if m != nil {
		return m.Host
	}
	return nil
}

func (m *Query) GetTargetHostSet() []string {
	if m != nil {
		return m.TargetHostSet
	}
	return nil
}

func (m *Query) GetUser() []string {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Query) GetTopicName() []string {
	if m != nil {
		return m.TopicName
	}
	return nil
}

func (m *Query) GetTagSet() []string {
	if m != nil {
		return m.TagSet
	}
	return nil
}

func (m *Query) GetParentEventId() []string {
	if m != nil {
		return m.ParentEventId
	}
	return nil
}

func (m *Query) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Query) GetStartEventTime() int64 {
	if m != nil {
		return m.StartEventTime
	}
	return 0
}

func (m *Query) GetEndEventTime() int64 {
	if m != nil {
		return m.EndEventTime
	}
	return 0
}

func (m *Query) GetStartReceivedTime() int64 {
	if m != nil {
		return m.StartReceivedTime
	}
	return 0
}

func (m *Query) GetEndReceivedTime() int64 {
	if m != nil {
		return m.EndReceivedTime
	}
	return 0
}

func (m *Query) GetSortField() []string {
	if m != nil {
		return m.SortField
	}
	return nil
}

func (m *Query) GetSortAscending() []bool {
	if m != nil {
		return m.SortAscending
	}
	return nil
}

func (m *Query) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Query) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type Topic struct {
	TopicName  string `protobuf:"bytes,1,opt,name=topic_name,json=topicName" json:"topic_name,omitempty"`
	DataSchema []byte `protobuf:"bytes,2,opt,name=data_schema,json=dataSchema,proto3" json:"data_schema,omitempty"`
}

func (m *Topic) Reset()                    { *m = Topic{} }
func (m *Topic) String() string            { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()               {}
func (*Topic) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Topic) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *Topic) GetDataSchema() []byte {
	if m != nil {
		return m.DataSchema
	}
	return nil
}

type UpdateTopicRequest struct {
	OldName    string `protobuf:"bytes,1,opt,name=old_name,json=oldName" json:"old_name,omitempty"`
	NewName    string `protobuf:"bytes,2,opt,name=new_name,json=newName" json:"new_name,omitempty"`
	DataSchema []byte `protobuf:"bytes,3,opt,name=data_schema,json=dataSchema,proto3" json:"data_schema,omitempty"`
}

func (m *UpdateTopicRequest) Reset()                    { *m = UpdateTopicRequest{} }
func (m *UpdateTopicRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateTopicRequest) ProtoMessage()               {}
func (*UpdateTopicRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UpdateTopicRequest) GetOldName() string {
	if m != nil {
		return m.OldName
	}
	return ""
}

func (m *UpdateTopicRequest) GetNewName() string {
	if m != nil {
		return m.NewName
	}
	return ""
}

func (m *UpdateTopicRequest) GetDataSchema() []byte {
	if m != nil {
		return m.DataSchema
	}
	return nil
}

type DeleteTopicRequest struct {
	TopicName string `protobuf:"bytes,1,opt,name=topic_name,json=topicName" json:"topic_name,omitempty"`
}

func (m *DeleteTopicRequest) Reset()                    { *m = DeleteTopicRequest{} }
func (m *DeleteTopicRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteTopicRequest) ProtoMessage()               {}
func (*DeleteTopicRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DeleteTopicRequest) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

type Dc struct {
	Dc string `protobuf:"bytes,1,opt,name=dc" json:"dc,omitempty"`
}

func (m *Dc) Reset()                    { *m = Dc{} }
func (m *Dc) String() string            { return proto.CompactTextString(m) }
func (*Dc) ProtoMessage()               {}
func (*Dc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Dc) GetDc() string {
	if m != nil {
		return m.Dc
	}
	return ""
}

type UpdateDcRequest struct {
	OldName string `protobuf:"bytes,1,opt,name=old_name,json=oldName" json:"old_name,omitempty"`
	NewName string `protobuf:"bytes,2,opt,name=new_name,json=newName" json:"new_name,omitempty"`
}

func (m *UpdateDcRequest) Reset()                    { *m = UpdateDcRequest{} }
func (m *UpdateDcRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateDcRequest) ProtoMessage()               {}
func (*UpdateDcRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UpdateDcRequest) GetOldName() string {
	if m != nil {
		return m.OldName
	}
	return ""
}

func (m *UpdateDcRequest) GetNewName() string {
	if m != nil {
		return m.NewName
	}
	return ""
}

type WriteResponse struct {
	Errcode int32  `protobuf:"varint,1,opt,name=errcode" json:"errcode,omitempty"`
	Errmsg  string `protobuf:"bytes,2,opt,name=errmsg" json:"errmsg,omitempty"`
	Id      string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
}

func (m *WriteResponse) Reset()                    { *m = WriteResponse{} }
func (m *WriteResponse) String() string            { return proto.CompactTextString(m) }
func (*WriteResponse) ProtoMessage()               {}
func (*WriteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *WriteResponse) GetErrcode() int32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *WriteResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *WriteResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Event)(nil), "eventmaster.Event")
	proto.RegisterType((*Query)(nil), "eventmaster.Query")
	proto.RegisterType((*Topic)(nil), "eventmaster.Topic")
	proto.RegisterType((*UpdateTopicRequest)(nil), "eventmaster.UpdateTopicRequest")
	proto.RegisterType((*DeleteTopicRequest)(nil), "eventmaster.DeleteTopicRequest")
	proto.RegisterType((*Dc)(nil), "eventmaster.Dc")
	proto.RegisterType((*UpdateDcRequest)(nil), "eventmaster.UpdateDcRequest")
	proto.RegisterType((*WriteResponse)(nil), "eventmaster.WriteResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for EventMaster service

type EventMasterClient interface {
	AddEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*WriteResponse, error)
	GetEvents(ctx context.Context, in *Query, opts ...grpc.CallOption) (EventMaster_GetEventsClient, error)
	AddTopic(ctx context.Context, in *Topic, opts ...grpc.CallOption) (*WriteResponse, error)
	UpdateTopic(ctx context.Context, in *UpdateTopicRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	DeleteTopic(ctx context.Context, in *DeleteTopicRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	AddDc(ctx context.Context, in *Dc, opts ...grpc.CallOption) (*WriteResponse, error)
	UpdateDc(ctx context.Context, in *UpdateDcRequest, opts ...grpc.CallOption) (*WriteResponse, error)
}

type eventMasterClient struct {
	cc *grpc.ClientConn
}

func NewEventMasterClient(cc *grpc.ClientConn) EventMasterClient {
	return &eventMasterClient{cc}
}

func (c *eventMasterClient) AddEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*WriteResponse, error) {
	out := new(WriteResponse)
	err := grpc.Invoke(ctx, "/eventmaster.EventMaster/AddEvent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventMasterClient) GetEvents(ctx context.Context, in *Query, opts ...grpc.CallOption) (EventMaster_GetEventsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_EventMaster_serviceDesc.Streams[0], c.cc, "/eventmaster.EventMaster/GetEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &eventMasterGetEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EventMaster_GetEventsClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type eventMasterGetEventsClient struct {
	grpc.ClientStream
}

func (x *eventMasterGetEventsClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *eventMasterClient) AddTopic(ctx context.Context, in *Topic, opts ...grpc.CallOption) (*WriteResponse, error) {
	out := new(WriteResponse)
	err := grpc.Invoke(ctx, "/eventmaster.EventMaster/AddTopic", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventMasterClient) UpdateTopic(ctx context.Context, in *UpdateTopicRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	out := new(WriteResponse)
	err := grpc.Invoke(ctx, "/eventmaster.EventMaster/UpdateTopic", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventMasterClient) DeleteTopic(ctx context.Context, in *DeleteTopicRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	out := new(WriteResponse)
	err := grpc.Invoke(ctx, "/eventmaster.EventMaster/DeleteTopic", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventMasterClient) AddDc(ctx context.Context, in *Dc, opts ...grpc.CallOption) (*WriteResponse, error) {
	out := new(WriteResponse)
	err := grpc.Invoke(ctx, "/eventmaster.EventMaster/AddDc", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventMasterClient) UpdateDc(ctx context.Context, in *UpdateDcRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	out := new(WriteResponse)
	err := grpc.Invoke(ctx, "/eventmaster.EventMaster/UpdateDc", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EventMaster service

type EventMasterServer interface {
	AddEvent(context.Context, *Event) (*WriteResponse, error)
	GetEvents(*Query, EventMaster_GetEventsServer) error
	AddTopic(context.Context, *Topic) (*WriteResponse, error)
	UpdateTopic(context.Context, *UpdateTopicRequest) (*WriteResponse, error)
	DeleteTopic(context.Context, *DeleteTopicRequest) (*WriteResponse, error)
	AddDc(context.Context, *Dc) (*WriteResponse, error)
	UpdateDc(context.Context, *UpdateDcRequest) (*WriteResponse, error)
}

func RegisterEventMasterServer(s *grpc.Server, srv EventMasterServer) {
	s.RegisterService(&_EventMaster_serviceDesc, srv)
}

func _EventMaster_AddEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventMasterServer).AddEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eventmaster.EventMaster/AddEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventMasterServer).AddEvent(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventMaster_GetEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Query)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventMasterServer).GetEvents(m, &eventMasterGetEventsServer{stream})
}

type EventMaster_GetEventsServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type eventMasterGetEventsServer struct {
	grpc.ServerStream
}

func (x *eventMasterGetEventsServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

func _EventMaster_AddTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Topic)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventMasterServer).AddTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eventmaster.EventMaster/AddTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventMasterServer).AddTopic(ctx, req.(*Topic))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventMaster_UpdateTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventMasterServer).UpdateTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eventmaster.EventMaster/UpdateTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventMasterServer).UpdateTopic(ctx, req.(*UpdateTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventMaster_DeleteTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventMasterServer).DeleteTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eventmaster.EventMaster/DeleteTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventMasterServer).DeleteTopic(ctx, req.(*DeleteTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventMaster_AddDc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Dc)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventMasterServer).AddDc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eventmaster.EventMaster/AddDc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventMasterServer).AddDc(ctx, req.(*Dc))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventMaster_UpdateDc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventMasterServer).UpdateDc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eventmaster.EventMaster/UpdateDc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventMasterServer).UpdateDc(ctx, req.(*UpdateDcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventMaster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "eventmaster.EventMaster",
	HandlerType: (*EventMasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddEvent",
			Handler:    _EventMaster_AddEvent_Handler,
		},
		{
			MethodName: "AddTopic",
			Handler:    _EventMaster_AddTopic_Handler,
		},
		{
			MethodName: "UpdateTopic",
			Handler:    _EventMaster_UpdateTopic_Handler,
		},
		{
			MethodName: "DeleteTopic",
			Handler:    _EventMaster_DeleteTopic_Handler,
		},
		{
			MethodName: "AddDc",
			Handler:    _EventMaster_AddDc_Handler,
		},
		{
			MethodName: "UpdateDc",
			Handler:    _EventMaster_UpdateDc_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEvents",
			Handler:       _EventMaster_GetEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "eventmaster.proto",
}

func init() { proto.RegisterFile("eventmaster.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 664 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x55, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0x6e, 0xe2, 0x3a, 0x4e, 0x26, 0xff, 0xda, 0xfd, 0x55, 0x3f, 0x96, 0x0a, 0xd4, 0xca, 0x02,
	0x54, 0x71, 0xa8, 0x10, 0x95, 0xe0, 0xc2, 0xa5, 0x52, 0xda, 0x82, 0x04, 0x48, 0x75, 0x8b, 0x38,
	0x46, 0xc6, 0x1e, 0x52, 0x8b, 0x24, 0x0e, 0xde, 0x6d, 0x11, 0x0f, 0xc2, 0xeb, 0xf1, 0x1e, 0xdc,
	0x98, 0x9d, 0xb5, 0x8b, 0xed, 0x86, 0xa6, 0x12, 0xb7, 0x9d, 0x6f, 0xbe, 0xf9, 0x66, 0x76, 0x66,
	0xd6, 0x86, 0x4d, 0xbc, 0xc2, 0xb9, 0x9e, 0x85, 0x4a, 0x63, 0xb6, 0xbf, 0xc8, 0x52, 0x9d, 0x8a,
	0x6e, 0x09, 0xf2, 0x7f, 0x34, 0xc1, 0x3d, 0x32, 0xb6, 0xb8, 0x0f, 0x6d, 0x76, 0x8c, 0x93, 0x58,
	0x36, 0x76, 0x1b, 0x7b, 0x9d, 0xc0, 0x63, 0xfb, 0x4d, 0x2c, 0x9e, 0xc0, 0x70, 0x11, 0x66, 0xc6,
	0x77, 0xcd, 0x68, 0x32, 0xa3, 0x6f, 0xe1, 0xa3, 0x9c, 0xf7, 0x10, 0xc0, 0x12, 0x74, 0x32, 0x43,
	0xe9, 0x10, 0xc5, 0x09, 0x3a, 0x8c, 0x9c, 0x13, 0x20, 0x06, 0xd0, 0x8c, 0x23, 0xb9, 0xce, 0x91,
	0x74, 0x32, 0x74, 0x9d, 0x2e, 0x92, 0x68, 0x3c, 0x0f, 0x89, 0xee, 0x32, 0xde, 0x61, 0xe4, 0x3d,
	0x01, 0xe2, 0x1e, 0x78, 0x3a, 0x9c, 0x8c, 0x15, 0x6a, 0xd9, 0xda, 0x75, 0xc8, 0xd7, 0x22, 0xf3,
	0x0c, 0xb5, 0x10, 0xb0, 0x7e, 0x91, 0x2a, 0x2d, 0x3d, 0x8e, 0xe0, 0xb3, 0x29, 0x51, 0x87, 0xd9,
	0x04, 0xf5, 0xd8, 0x98, 0x1c, 0xd4, 0xe6, 0xa0, 0xbe, 0x85, 0x5f, 0x13, 0x9a, 0xc7, 0x5e, 0x2a,
	0xcc, 0x64, 0xc7, 0xc6, 0x9a, 0xb3, 0xc1, 0xe2, 0x50, 0x87, 0x12, 0x08, 0xeb, 0x05, 0x7c, 0xf6,
	0x7f, 0x39, 0xe0, 0x9e, 0x5e, 0x62, 0xf6, 0x3d, 0xaf, 0xba, 0xc1, 0x62, 0xa6, 0xea, 0x22, 0x7b,
	0x93, 0x91, 0xbf, 0x66, 0x77, 0x6e, 0xcb, 0xbe, 0x6e, 0x63, 0x39, 0x7b, 0xbd, 0x0b, 0xce, 0x1d,
	0xbb, 0xb0, 0x64, 0x28, 0x9e, 0xcd, 0x59, 0x1d, 0x4a, 0x71, 0xbb, 0xb6, 0xbd, 0xb1, 0x39, 0x8b,
	0x3d, 0xd8, 0x50, 0x54, 0x59, 0x11, 0xca, 0xe3, 0xea, 0xf0, 0xb8, 0x06, 0x8c, 0x1f, 0x5d, 0xcf,
	0xec, 0x11, 0x0c, 0x70, 0x1e, 0x97, 0x79, 0xc0, 0xbc, 0x1e, 0xa1, 0x7f, 0x58, 0xfb, 0xf0, 0x9f,
	0xd5, 0xcb, 0x30, 0xc2, 0xe4, 0x0a, 0x63, 0x4b, 0xed, 0x32, 0x75, 0x93, 0x5d, 0x41, 0xee, 0x61,
	0xfe, 0x53, 0xda, 0x4b, 0x52, 0xad, 0xb2, 0x7b, 0xcc, 0x1e, 0x92, 0xa3, 0xc2, 0xa5, 0xfe, 0xa8,
	0x94, 0xa4, 0x3f, 0x27, 0x38, 0x8d, 0x65, 0xdf, 0xf6, 0xc7, 0x20, 0xc7, 0x06, 0x10, 0x8f, 0x61,
	0xc0, 0xee, 0x50, 0x45, 0x14, 0x99, 0xcc, 0x27, 0x72, 0x40, 0x94, 0x76, 0xd0, 0x37, 0xe8, 0x61,
	0x01, 0x8a, 0x2d, 0x70, 0xb9, 0x0c, 0x39, 0xa4, 0x2c, 0x6e, 0x60, 0x0d, 0x83, 0x4e, 0x93, 0x59,
	0xa2, 0xe5, 0x86, 0x45, 0xd9, 0xf0, 0x4f, 0xc0, 0x3d, 0x37, 0xfd, 0xaf, 0x8d, 0xa6, 0x51, 0x5f,
	0xd0, 0x1d, 0xe8, 0x9a, 0x6e, 0x8e, 0x55, 0x74, 0x81, 0xb3, 0x90, 0x9f, 0x44, 0x2f, 0x00, 0x03,
	0x9d, 0x31, 0xe2, 0x7f, 0x01, 0xf1, 0x61, 0x41, 0x36, 0xb2, 0x5c, 0x80, 0x5f, 0x2f, 0x51, 0xf1,
	0x43, 0x4b, 0xa7, 0x71, 0x59, 0xd3, 0x23, 0x9b, 0x15, 0xc9, 0x35, 0xc7, 0x6f, 0xd6, 0x65, 0x5f,
	0x98, 0x47, 0xf6, 0xb2, 0x64, 0xce, 0x8d, 0x64, 0x07, 0x20, 0x46, 0x38, 0xc5, 0x5a, 0xb2, 0xdb,
	0xaf, 0xe0, 0x6f, 0x41, 0x73, 0x14, 0x5d, 0xaf, 0x78, 0xfe, 0x30, 0xa9, 0x01, 0x43, 0x5b, 0xf7,
	0xe8, 0xdf, 0x8a, 0xf6, 0x4f, 0xa1, 0xff, 0x31, 0x4b, 0x34, 0x06, 0xa8, 0x16, 0xe9, 0x5c, 0xa1,
	0x90, 0xe0, 0x61, 0x96, 0x45, 0x69, 0x6c, 0x55, 0xdc, 0xa0, 0x30, 0xc5, 0xff, 0xd0, 0xa2, 0xe3,
	0x4c, 0x4d, 0x72, 0x8d, 0xdc, 0x32, 0xb5, 0xd1, 0x66, 0x3b, 0xb6, 0xb6, 0x24, 0x7e, 0xfe, 0xd3,
	0x81, 0x2e, 0x2f, 0xde, 0x3b, 0xfe, 0x80, 0x89, 0x57, 0xd0, 0x3e, 0x8c, 0xed, 0x2a, 0x0a, 0xb1,
	0x5f, 0xfe, 0xda, 0x31, 0xb6, 0xbd, 0x5d, 0xc1, 0x2a, 0xd5, 0xf8, 0x6b, 0xe2, 0x25, 0x74, 0x4e,
	0xd0, 0xae, 0xbb, 0xaa, 0x85, 0xf3, 0xeb, 0xdf, 0x5e, 0x22, 0xe9, 0xaf, 0x3d, 0x6b, 0xe4, 0x69,
	0xed, 0x9a, 0x54, 0x39, 0x8c, 0xad, 0x48, 0xfb, 0x16, 0xba, 0xa5, 0xc5, 0x10, 0x3b, 0x15, 0xf2,
	0xcd, 0x95, 0x59, 0xad, 0x56, 0x9a, 0x7c, 0x4d, 0xed, 0xe6, 0x4e, 0xac, 0x50, 0x7b, 0x01, 0x2e,
	0xdd, 0x8c, 0xb6, 0x62, 0x58, 0xd5, 0x59, 0x75, 0xa7, 0x63, 0x68, 0x17, 0x4b, 0x23, 0x1e, 0x2c,
	0xb9, 0xd0, 0xe8, 0x6e, 0xf9, 0x3f, 0xb5, 0xf8, 0x2f, 0x75, 0xf0, 0x3b, 0x00, 0x00, 0xff, 0xff,
	0x8a, 0x12, 0x5b, 0xcf, 0xba, 0x06, 0x00, 0x00,
}
