// Code generated by protoc-gen-go.
// source: eventmaster.proto
// DO NOT EDIT!

/*
Package eventmaster is a generated protocol buffer package.

It is generated from these files:
	eventmaster.proto

It has these top-level messages:
	Event
	WriteResponse
	Query
	HealthcheckRequest
	HealthcheckResponse
*/
package eventmaster

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event struct {
	ParentEventId string   `protobuf:"bytes,1,opt,name=parent_event_id,json=parentEventId" json:"parent_event_id,omitempty"`
	EventTime     int64    `protobuf:"varint,2,opt,name=event_time,json=eventTime" json:"event_time,omitempty"`
	Dc            string   `protobuf:"bytes,3,opt,name=dc" json:"dc,omitempty"`
	TopicName     string   `protobuf:"bytes,4,opt,name=topic_name,json=topicName" json:"topic_name,omitempty"`
	TagSet        []string `protobuf:"bytes,5,rep,name=tag_set,json=tagSet" json:"tag_set,omitempty"`
	Host          string   `protobuf:"bytes,6,opt,name=host" json:"host,omitempty"`
	TargetHostSet []string `protobuf:"bytes,7,rep,name=target_host_set,json=targetHostSet" json:"target_host_set,omitempty"`
	User          string   `protobuf:"bytes,8,opt,name=user" json:"user,omitempty"`
	DataJson      string   `protobuf:"bytes,9,opt,name=data_json,json=dataJson" json:"data_json,omitempty"`
	EventType     int32    `protobuf:"varint,10,opt,name=event_type,json=eventType" json:"event_type,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Event) GetParentEventId() string {
	if m != nil {
		return m.ParentEventId
	}
	return ""
}

func (m *Event) GetEventTime() int64 {
	if m != nil {
		return m.EventTime
	}
	return 0
}

func (m *Event) GetDc() string {
	if m != nil {
		return m.Dc
	}
	return ""
}

func (m *Event) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *Event) GetTagSet() []string {
	if m != nil {
		return m.TagSet
	}
	return nil
}

func (m *Event) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Event) GetTargetHostSet() []string {
	if m != nil {
		return m.TargetHostSet
	}
	return nil
}

func (m *Event) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Event) GetDataJson() string {
	if m != nil {
		return m.DataJson
	}
	return ""
}

func (m *Event) GetEventType() int32 {
	if m != nil {
		return m.EventType
	}
	return 0
}

type WriteResponse struct {
	Errcode int32  `protobuf:"varint,1,opt,name=errcode" json:"errcode,omitempty"`
	Errmsg  string `protobuf:"bytes,2,opt,name=errmsg" json:"errmsg,omitempty"`
	EventId string `protobuf:"bytes,3,opt,name=event_id,json=eventId" json:"event_id,omitempty"`
}

func (m *WriteResponse) Reset()                    { *m = WriteResponse{} }
func (m *WriteResponse) String() string            { return proto.CompactTextString(m) }
func (*WriteResponse) ProtoMessage()               {}
func (*WriteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *WriteResponse) GetErrcode() int32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *WriteResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *WriteResponse) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

type Query struct {
	Dc         []string `protobuf:"bytes,1,rep,name=dc" json:"dc,omitempty"`
	Host       []string `protobuf:"bytes,2,rep,name=host" json:"host,omitempty"`
	TargetHost []string `protobuf:"bytes,3,rep,name=target_host,json=targetHost" json:"target_host,omitempty"`
	TopicName  []string `protobuf:"bytes,4,rep,name=topic_name,json=topicName" json:"topic_name,omitempty"`
	TagSet     []string `protobuf:"bytes,5,rep,name=tag_set,json=tagSet" json:"tag_set,omitempty"`
	StartTime  int64    `protobuf:"varint,6,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	EndTime    int64    `protobuf:"varint,7,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
}

func (m *Query) Reset()                    { *m = Query{} }
func (m *Query) String() string            { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()               {}
func (*Query) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Query) GetDc() []string {
	if m != nil {
		return m.Dc
	}
	return nil
}

func (m *Query) GetHost() []string {
	if m != nil {
		return m.Host
	}
	return nil
}

func (m *Query) GetTargetHost() []string {
	if m != nil {
		return m.TargetHost
	}
	return nil
}

func (m *Query) GetTopicName() []string {
	if m != nil {
		return m.TopicName
	}
	return nil
}

func (m *Query) GetTagSet() []string {
	if m != nil {
		return m.TagSet
	}
	return nil
}

func (m *Query) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Query) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

type HealthcheckRequest struct {
}

func (m *HealthcheckRequest) Reset()                    { *m = HealthcheckRequest{} }
func (m *HealthcheckRequest) String() string            { return proto.CompactTextString(m) }
func (*HealthcheckRequest) ProtoMessage()               {}
func (*HealthcheckRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type HealthcheckResponse struct {
	Response string `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
}

func (m *HealthcheckResponse) Reset()                    { *m = HealthcheckResponse{} }
func (m *HealthcheckResponse) String() string            { return proto.CompactTextString(m) }
func (*HealthcheckResponse) ProtoMessage()               {}
func (*HealthcheckResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *HealthcheckResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func init() {
	proto.RegisterType((*Event)(nil), "eventmaster.Event")
	proto.RegisterType((*WriteResponse)(nil), "eventmaster.WriteResponse")
	proto.RegisterType((*Query)(nil), "eventmaster.Query")
	proto.RegisterType((*HealthcheckRequest)(nil), "eventmaster.HealthcheckRequest")
	proto.RegisterType((*HealthcheckResponse)(nil), "eventmaster.HealthcheckResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for EventMaster service

type EventMasterClient interface {
	FireEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*WriteResponse, error)
	GetEvents(ctx context.Context, in *Query, opts ...grpc.CallOption) (EventMaster_GetEventsClient, error)
	Healthcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error)
}

type eventMasterClient struct {
	cc *grpc.ClientConn
}

func NewEventMasterClient(cc *grpc.ClientConn) EventMasterClient {
	return &eventMasterClient{cc}
}

func (c *eventMasterClient) FireEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*WriteResponse, error) {
	out := new(WriteResponse)
	err := grpc.Invoke(ctx, "/eventmaster.EventMaster/FireEvent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventMasterClient) GetEvents(ctx context.Context, in *Query, opts ...grpc.CallOption) (EventMaster_GetEventsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_EventMaster_serviceDesc.Streams[0], c.cc, "/eventmaster.EventMaster/GetEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &eventMasterGetEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EventMaster_GetEventsClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type eventMasterGetEventsClient struct {
	grpc.ClientStream
}

func (x *eventMasterGetEventsClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *eventMasterClient) Healthcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error) {
	out := new(HealthcheckResponse)
	err := grpc.Invoke(ctx, "/eventmaster.EventMaster/Healthcheck", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EventMaster service

type EventMasterServer interface {
	FireEvent(context.Context, *Event) (*WriteResponse, error)
	GetEvents(*Query, EventMaster_GetEventsServer) error
	Healthcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error)
}

func RegisterEventMasterServer(s *grpc.Server, srv EventMasterServer) {
	s.RegisterService(&_EventMaster_serviceDesc, srv)
}

func _EventMaster_FireEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventMasterServer).FireEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eventmaster.EventMaster/FireEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventMasterServer).FireEvent(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventMaster_GetEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Query)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventMasterServer).GetEvents(m, &eventMasterGetEventsServer{stream})
}

type EventMaster_GetEventsServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type eventMasterGetEventsServer struct {
	grpc.ServerStream
}

func (x *eventMasterGetEventsServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

func _EventMaster_Healthcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthcheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventMasterServer).Healthcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eventmaster.EventMaster/Healthcheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventMasterServer).Healthcheck(ctx, req.(*HealthcheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventMaster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "eventmaster.EventMaster",
	HandlerType: (*EventMasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FireEvent",
			Handler:    _EventMaster_FireEvent_Handler,
		},
		{
			MethodName: "Healthcheck",
			Handler:    _EventMaster_Healthcheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEvents",
			Handler:       _EventMaster_GetEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "eventmaster.proto",
}

func init() { proto.RegisterFile("eventmaster.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 461 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x93, 0xcf, 0x8e, 0xd3, 0x40,
	0x0c, 0xc6, 0x37, 0xed, 0x26, 0x69, 0x5c, 0x15, 0x84, 0x41, 0x30, 0x04, 0xa1, 0xad, 0x72, 0x40,
	0x9c, 0x56, 0xfc, 0x39, 0x70, 0xe2, 0x08, 0x2c, 0x48, 0x20, 0x11, 0x90, 0xb8, 0x20, 0x45, 0x21,
	0xb1, 0xda, 0x00, 0x4d, 0xc2, 0xcc, 0x14, 0x69, 0x5f, 0x87, 0x07, 0xe1, 0x3d, 0x78, 0x1b, 0x3c,
	0x9e, 0x74, 0x49, 0x29, 0x48, 0x7b, 0xb3, 0x7f, 0xf6, 0x17, 0x8d, 0x3f, 0x3b, 0x70, 0x8d, 0xbe,
	0x53, 0x6b, 0x37, 0xa5, 0xb1, 0xa4, 0x4f, 0x7b, 0xdd, 0xd9, 0x0e, 0xe7, 0x23, 0x94, 0xfd, 0x98,
	0x40, 0xf8, 0xcc, 0xe5, 0x78, 0x0f, 0xae, 0xf6, 0xa5, 0xe6, 0xa8, 0x90, 0x7a, 0xd1, 0xd4, 0x2a,
	0x58, 0x06, 0xf7, 0x93, 0x7c, 0xe1, 0xb1, 0x74, 0xbd, 0xac, 0xf1, 0x2e, 0x80, 0x6f, 0xb0, 0xcd,
	0x86, 0xd4, 0x84, 0x5b, 0xa6, 0x79, 0x22, 0xe4, 0x3d, 0x03, 0xbc, 0x02, 0x93, 0xba, 0x52, 0x53,
	0x51, 0x72, 0xe4, 0xda, 0x6d, 0xd7, 0x37, 0x55, 0xd1, 0x96, 0xdc, 0x7e, 0x2c, 0x3c, 0x11, 0xf2,
	0x86, 0x01, 0xde, 0x82, 0xd8, 0x96, 0xab, 0xc2, 0x90, 0x55, 0xe1, 0x72, 0xca, 0xb5, 0x88, 0xd3,
	0x77, 0x64, 0x11, 0xe1, 0x78, 0xdd, 0x19, 0xab, 0x22, 0x51, 0x48, 0xec, 0x9e, 0x68, 0x4b, 0xbd,
	0x22, 0x5b, 0xb8, 0x54, 0x44, 0xb1, 0x88, 0x16, 0x1e, 0x9f, 0x31, 0x1d, 0xb4, 0x5b, 0x43, 0x5a,
	0xcd, 0xbc, 0xd6, 0xc5, 0x78, 0x07, 0x92, 0xba, 0xb4, 0x65, 0xf1, 0xd9, 0x74, 0xad, 0x4a, 0xa4,
	0x30, 0x73, 0xe0, 0x15, 0xe7, 0xa3, 0x99, 0xce, 0x7b, 0x52, 0xc0, 0xd5, 0x70, 0x37, 0x13, 0x83,
	0xec, 0x23, 0x2c, 0x3e, 0xe8, 0xc6, 0x52, 0x4e, 0xa6, 0xef, 0x5a, 0x43, 0xa8, 0x20, 0x26, 0xad,
	0xab, 0xae, 0x26, 0xf1, 0x28, 0xcc, 0x77, 0x29, 0xde, 0x84, 0x88, 0xc3, 0x8d, 0x59, 0x89, 0x33,
	0x3c, 0x8e, 0xcf, 0xf0, 0x36, 0xcc, 0x2e, 0x6c, 0xf5, 0xe6, 0xc4, 0xe4, 0x0d, 0xcd, 0x7e, 0x06,
	0x10, 0xbe, 0xdd, 0x92, 0x3e, 0x1f, 0xbc, 0x0b, 0x64, 0x24, 0xe7, 0xdd, 0xce, 0x83, 0x89, 0x10,
	0xef, 0xc1, 0x09, 0xcc, 0x47, 0x1e, 0xf0, 0xb7, 0x5c, 0x09, 0xfe, 0xcc, 0x7f, 0x60, 0xf8, 0xf4,
	0x92, 0x86, 0xb3, 0xce, 0xf0, 0x67, 0x86, 0xbd, 0x46, 0x7e, 0xaf, 0x42, 0x64, 0xaf, 0x6e, 0x80,
	0xb6, 0xf6, 0xc5, 0x58, 0x8a, 0x31, 0xe7, 0xae, 0x94, 0xdd, 0x00, 0x3c, 0xa3, 0xf2, 0xab, 0x5d,
	0x57, 0x6b, 0xaa, 0xbe, 0xe4, 0xf4, 0x6d, 0x4b, 0xc6, 0x66, 0x0f, 0xe1, 0xfa, 0x1e, 0x1d, 0xac,
	0x4b, 0x61, 0xa6, 0x87, 0x78, 0xb8, 0xaf, 0x8b, 0xfc, 0xd1, 0xaf, 0x00, 0xe6, 0x72, 0x66, 0xaf,
	0xe5, 0x38, 0xf1, 0x29, 0x24, 0xcf, 0x1b, 0x4d, 0xfe, 0x3e, 0xf1, 0x74, 0x7c, 0xca, 0xc2, 0xd2,
	0x74, 0x8f, 0xed, 0xed, 0x28, 0x3b, 0xc2, 0x27, 0x90, 0xbc, 0x20, 0x7f, 0xb7, 0xe6, 0x2f, 0xb9,
	0xf8, 0x9d, 0xfe, 0xe3, 0x93, 0xd9, 0xd1, 0x83, 0x00, 0x73, 0x98, 0x8f, 0x9e, 0x8e, 0x27, 0x7b,
	0x6d, 0x87, 0xa3, 0xa6, 0xcb, 0xff, 0x37, 0xec, 0x1e, 0xf3, 0x29, 0x92, 0x9f, 0xef, 0xf1, 0xef,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x85, 0x52, 0x1d, 0xbc, 0x91, 0x03, 0x00, 0x00,
}
